library(Biostrings)


sq <- DNAString(x = "ACCAATGAAATAAAGTGAAAGCCCGAATTCCATGGCAGCTATGCAAACTGTCGCAGCTTACGCAGTTCCTTATCCCGCTCTCGACATTCTTGCTGACCAGAAACGTCAAGCGTCAAGCCATAGGAATCATCACTTGTTAGTGGACTATAACCCATAAGCATATGCCGCATTTCCGGCGTATCAGTAACCATGCAATTTGTACCCCTGTAGGCGAAATTATAACTGGCCTGGAGCCTCGTACGACTGGTACTCTGAATTCTTTTAATCAAGTGGATTGAAGATCTTTTATGGCGAAAACCTCGAGAGATGGTTTACAGCCTCTTGCTTTCTAACTCGAAACTGGTATCGCCATATGGTCGCGTTATTGAAATTATCCTGGATAACATGTATAGCTGCCTAGCAACCAAAGCCAAGAAGTGACCGGATGTCGAGCTCGAGTGCATCGTCGAAAGCATATTGACTGTCACTCCGCCGGTCATCGTGCTGATATTGACGATTGGCTATGCTTCGGTCCCACGGCATTGCAGAGGGATGCGCCTTGTCAAAAGATCATGGTCTGGGTGAACAACCACAGATTCTATGGCGTCAGGAAAAAAGACAACATAGTGGCGCAGATCAAGGAACATTTCGTGAATTTATTGCTTGATTTATAGGCAGCTGTGCCGCGTGCTTATACGTACTGCTGTGGGCACCGAACGAAGAACTTTCGACAGACCCTGGCTACACAATTTCTGGAATAAGGAGATTGTGATTGAGTCACTCTGGCCTGTTTGTTTGTGAATGCTCTCTGTTCAGCCAATAATGTGAGGCGTCTATACCGTACTTGCCGCTCTATCGCCACAGTTAGATATCGGCGCATAGTTATCGTCATGCCATAGCCACATTGACGCATATACATATAGTAACAAGTATCCTTACCGTGAAGATACGTCCCATAGTGTTCTATACTGACCTCTGCACTCTCCATGTTAGTTTCAGACGGCTCTTCAACGTACAGTGAGATCACTGCCCCGTAGCCACAATACCTCACTGAGAGATATGTCCTTCATTCTTCTTGCAGGAGTATGAGTTACCATAAAGAGTCGTCCGGGTCTATGGGTGCTCAAATATGAAACTTCCAAGTATCTCGCACTAGTTCGCATTCTATTGGTGAATACTGAGCATCAAGCGCAGGTATCGGAATGGGCTTGCTTTACGCAACCCGTCACTTATAGGGCTGGAACCGCTGCACACTGTGCCCCAACGGTGGCCTCCCTTGAAGCTATACCAGCGTCCTGCTTTTGGGAGCGAGTATGAAGTATGTCTTGCTTAGCCACATACTTTTTGTATATAGACTAGCGTACTCTCGCGGTTTGTGGTCTACAAGATTCCAGCAAAGACCGTCCACAATTACTATATAGGCCATCACCAGCACAACACCTCCATCTCGCTTCCACCCTGAGCGAATATTTTCCTGTCAATAGTATCCTGTCCTAGTTTAGATGACTTCTGTGTTGTCAGCAACCATATCTTGCGCATTCTCACCAGCTGCATCAGCTTCCTAGACTTGTTCTTCTGAGTAATACTATCACTAGCACTTCCAGAAAGATCTATTACGCCATAAGCAGGCTGTGAAATTTCTAGTAGATGCGGCAGGCAGTTAAAAATCCCACAGAGAATGTGTTCTATTGGGTGCGTTCCCTGCATCGGAGACATAGTCGGAGACTTCCCATCTATTTTAGTGCGGCCTGAACCCTCTTCCACACCCAGTTTTCATCATCATCATCGTCATCATCATCACTACCGTCTCCCTAGAATAACATCTGCCTCGTCTCCTCACTCTCACTTAACCCCATATTAGGCACTAT")


letterFrequency(x = sq, letters="ATGC", OR=0) 
window <- 100
gc <- rowSums(letterFrequencyInSlidingView(x = sq, view.width = window, letters = c("G", "C")))/window

plot(gc, type = 'l')
plot(1:length(gc), gc)
lines(lowess(x = 1:length(gc), y= gc, f = 0.10), col = 12, lwd = 2)



df <- tibble(
  aa = c("P", "H", "D", "I", "S", "F", "U", "N"),
  lp = c(1, 0.2, 0.6, 0.4, 0.6, 0.2, 0.8, 0.7)
)

df$pos <- 1:nrow(df)

ggplot(data = df, mapping = aes(x = pos, y = 0)) +
  geom_text(mapping = aes(label = aa, size = lp)) +
  scale_size_continuous(range = c(10,40), breaks = NULL) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank()
  )


expand.grid(rep(list(c("A", "T", "G", "C")), 3))
combn(c("A", "T", "G", "C"), 3)
unique(t(combn(rep(c("A", "T", "G", "C"), 3),3)))









